FROM python:3.11-slim-buster as builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN python -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir build && \
    pip install --no-cache-dir -e ".[dev,nlp,vector]" && \
    pip install --no-cache-dir pre-commit

RUN chown -R 1000:1000 /opt/venv

FROM python:3.11-slim-buster

COPY --from=builder /opt/venv /opt/venv
RUN chown -R 1000:1000 /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN apt-get update && apt-get install -y --no-install-recommends \
    #libgomp \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -u 1000 appuser
USER appuser

WORKDIR /app
